### PR TITLE
Feature/flexdashboard xaringan templates

### PR DESCRIPTION
**Pull request by collinschwantes**
Created templates for xaringan and flex dashboards. Also fixed issues with dependencies, documentation, and out of date function calls for the pptx template.  #11 #12 #13 #14 

Flexdashboard template no longer requires dev version of bslib.

Avenir font is now hosted in [AWS S3](https://s3.console.aws.amazon.com/s3/buckets/font-avenir?region=us-east-2&tab=objects) as a woff2 file that can be used directly with `bslib` and helper css font face file for importing in `xaringanthemer`.

### CODE REVIEW

**Comment by noamross** [comment]
OK, there are a fair number of things that I think we should change.  Sorry I didn't give better guidance on some of this before! You dove in and started fixing things though I hadn't looked at in a long time.  

- There should be two themes and we should have both as both pptx and xaringan templates and should look pretty much the same between both versions. Let's call the themes "Classic" and "Avenir", so there should be four functions, `eha_classic_pptx`,  `eha_avenir_pptx`,  `eha_classic_xar`,  `eha_avenir_xar`.
    - Unfortunately the PPTX that was in the package doesn't really correspond to either format 😬.  The "classic" templates can be found at https://www.dropbox.com/sh/sxgunfg49zs1dcj/AABdXrS1rZ6SbIDXdb2ND7o9a/PPT%20Template?dl=0&subfolder_nav_tracking=1 .   The "Avenir" template should be the board presentation I shared with you on Slack. 
- It would be excellent if we could build the PowerPoint templates on top of `officedown::rpptx_document` instead of `rmarkdown::powerpoint_presentation`.  It has the killer feature of _editable_ plot outputs.  Try it out and use https://github.com/davidgohel/officedown/blob/master/inst/rmarkdown/templates/powerpoint/skeleton/skeleton.Rmd as the basis of the template.  This is a bit of a big refactor but I think you can drop much of the internal code of the current R function if you just update PPTX templates.  (You might have to use `officer:::get_default_pandoc_data_file(format = "pptx")` as your base to modify).  I don't think you need to add the image on top as we do there, just having it in the template title slide and the logo in the footer for regular slides.

- `eha_flex_dashboard`'s template should not require any arguments in the YAML, just
        
        title: "Template Title"
        output: 
           ehastyle::eha_flex_dashboard
    
    To get both default colors and Avenir font. It looks like this was the original plan but you commented information out?  You can explain changing header options in the help file. 

-  The README should give an overview of the package, key functions, with screenshots of the outputs.
-  Full descriptions in all function help files, (e.g. "This format generates HTML slides in EHA's classic theme.", "For additional options to pass to `...`, see [xaringan::moon_reader]", etc.)
- We should probably be adding testing + CI, but that can wait for a later moment.

**Comment by collinschwantes** [comment]
@noamross  Should be ready for review

**Comment by collinschwantes** [comment]
Having the same corrupt file issues with avenir and classic but not with the predict pptx formats. Avenir and Classic both have embedded in the their current iteration so I will try without the embedded fonts.

**Comment by collinschwantes** [comment]
I can knit using the predict pptx file as the template within the classic function so likely the ppt template.

**Comment by noamross** [comment]
Looking great!  I made a few small tweaks (some notes in the commit messages).  My only other request is for eha_helvetica_xar to have the same title background as eha_avenir_xar.

**Comment by noamross** [comment]
Realized this wasn't merged before your talk! We'll patch if needed.

**Pull request merged**
